version: "3"
services:
  # client:
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - type: bind
  #       source: ./client
  #       target: /code
  #   working_dir: /code
  #   command: bash -c "npm install"
  api:
    image: node:latest
    working_dir: /code
    ports:
      - 3000:3000
    environment:
      - PGUSER=bull
      - PGHOST=db
      - PGPASSWORD=bullpass
      - PGDATABASE=bull-db
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm start && npm run dev"

  db:
    image: postgres:latest
    ports:
      - 35432:5432
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db/:/docker-entrypoint-db_config/config.d/:ro"
    environment:
      - POSTGRES_DB=Bull-db
      - POSTGRES_USER=Bull
      - POSTGRES_PASSWORD=bullpass
volumes:
  dbdata:
